# Generated by Django 5.2.4 on 2026-04-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_id", models.CharField(max_length=100, unique=True)),
                ("sender", models.CharField(max_length=100)),
                ("receiver", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.FloatField()),
                ("nonce", models.IntegerField()),
                ("timestamp", models.FloatField()),
                ("status", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
