# Generated by Django 5.2.4 on 2026-05-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionqueue",
            name="next_attempt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transactionqueue",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transactionstatus",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
