# Generated by Django 5.2.4 on 2026-04-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_id", models.CharField(max_length=100, unique=True)),
                ("sender", models.CharField(max_length=100)),
                ("receiver", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                ("nonce", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("RETRY", "Retry"),
                            ("FAILED", "Failed"),
                            ("SUCCESS", "Success"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("retries", models.IntegerField(default=0)),
                ("next_attempt", models.FloatField(default=0)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
