# Generated by Django 5.2.4 on 2026-05-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_alter_transactionqueue_next_attempt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionqueue",
            name="next_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
