# Generated by Django 5.2.4 on 2026-04-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_transactionqueue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionstatus",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="transactionstatus",
            name="nonce",
        ),
        migrations.RemoveField(
            model_name="transactionstatus",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="transactionstatus",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="transactionstatus",
            name="timestamp",
        ),
    ]
