# Generated by Django 5.2.4 on 2026-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_alter_transactionqueue_next_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionqueue",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("RETRY", "Retry"),
                    ("FAILED", "Failed"),
                    ("SUCCESS", "Success"),
                    ("BUFFERED", "Buffered"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactionstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("RETRY", "Retry"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("BUFFERED", "Buffered"),
                ],
                max_length=20,
            ),
        ),
    ]
