# Generated by Django 5.2.4 on 2026-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_remove_transactionstatus_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionqueue",
            name="processing_started_at",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
