# Generated by Django 5.2.4 on 2026-05-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_transactionevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=55)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
