# Generated by Django 5.2.4 on 2026-05-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0007_ledgerevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerevent",
            name="tx_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
