# Generated by Django 5.2.4 on 2026-05-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0008_alter_ledgerevent_tx_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ledgerevent",
            name="id",
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="sequence",
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
