# Generated by Django 5.2.4 on 2026-05-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0009_remove_ledgerevent_id_ledgerevent_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=255, unique=True)),
                ("balance", models.FloatField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
