# Generated by Django 5.2.4 on 2026-06-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0010_accountprojection"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadLetterQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_id", models.CharField(max_length=100, unique=True)),
                ("sender", models.CharField(max_length=100)),
                ("receiver", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                ("nonce", models.IntegerField()),
                ("reason", models.TextField()),
                ("retries", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
